"""empty message

Revision ID: 203547da10a2
Revises: 
Create Date: 2017-10-17 13:02:07.522272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '203547da10a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billflow', sa.Column('p2p_id', sa.Integer(), nullable=True))
    op.add_column('billflow', sa.Column('type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'billflow', 'p2p', ['p2p_id'], ['id'])
    op.drop_column('billflow', 'action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billflow', sa.Column('action', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'billflow', type_='foreignkey')
    op.drop_column('billflow', 'type')
    op.drop_column('billflow', 'p2p_id')
    # ### end Alembic commands ###
