"""empty message

Revision ID: caf0f488528f
Revises: 95971a20adb3
Create Date: 2017-10-28 09:25:11.452706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf0f488528f'
down_revision = '95971a20adb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forgetpwd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('expiretime', sa.DateTime(), nullable=True),
    sa.Column('use', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forgetpwd')
    # ### end Alembic commands ###
