"""empty message

Revision ID: ccaed15190ca
Revises: 64ec2447b7d1
Create Date: 2017-10-25 12:08:22.744355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccaed15190ca'
down_revision = '64ec2447b7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forgetpwd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('expiretime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forgetpwd')
    # ### end Alembic commands ###
