"""empty message

Revision ID: e991376f8df9
Revises: 203547da10a2
Create Date: 2017-10-18 12:11:59.481114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e991376f8df9'
down_revision = '203547da10a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billflow', sa.Column('addtime', sa.DateTime(), nullable=True))
    op.add_column('billflow', sa.Column('donetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billflow', 'donetime')
    op.drop_column('billflow', 'addtime')
    # ### end Alembic commands ###
